# Generated by Django 5.1.1 on 2024-09-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_student_lastname_alter_student_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
    ]
