# Generated by Django 5.1.1 on 2024-09-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_student_lastname_alter_teacher_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dpi',
            field=models.IntegerField(max_length=50),
        ),
    ]
