# Generated by Django 5.1.1 on 2024-09-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_student_dpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dpi',
            field=models.CharField(max_length=50),
        ),
    ]
