# Generated by Django 5.1.1 on 2024-10-02 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='course',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
