# Generated by Django 5.1.1 on 2024-10-11 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Conductor', 'verbose_name_plural': 'Conductores'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='codigocurso',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('taxi', 'Taxi'), ('motoraton', 'Moto Raton'), ('tuctuc', 'Tuc Tuc'), ('mudanza', 'Mudanza')], default='taxi', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='modelo',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='placa',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='total_enrolled_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, default='Unnamed Course', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher'),
        ),
        migrations.CreateModel(
            name='EnrollmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('desmatriculacion', 'Desmatriculación'), ('cobro', 'Cobro/Expulsión')], default='desmatriculacion', max_length=20)),
                ('expulsion_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
        ),
    ]
