# Generated by Django 5.1.1 on 2024-10-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_course_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='end_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='start_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
