# Generated by Django 5.1.1 on 2024-10-18 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerServiceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntualidad', models.CharField(max_length=255)),
                ('limpieza_vehiculo', models.CharField(max_length=255)),
                ('asistencia_conductor', models.CharField(max_length=255)),
                ('conocimiento_rutas', models.CharField(max_length=255)),
                ('seguridad', models.CharField(max_length=255)),
                ('tarifas', models.CharField(max_length=255)),
                ('facilidad_reserva', models.CharField(max_length=255)),
                ('atencion_cliente', models.CharField(max_length=255)),
                ('comodidad_vehiculo', models.CharField(max_length=255)),
                ('experiencia_general', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
