# Generated by Django 5.1.1 on 2024-10-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customerserviceform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerserviceform',
            name='student',
        ),
    ]
